---
- hosts: corespace
  become: yes
  roles:
    - network
    - xbps-repoconf
    - core-daemons
    - core-programs
    - sshd
    - mosh
    - bitlbee
    - irc-session
    - acmetool
    - pydio
    - xbps-mini-repo
