---
network_output_policy: ACCEPT
network_input_policy: ACCEPT
network_forward_policy: ACCEPT
network_hostname: global-dynamics

network_boot_hosts:
  - name: mirrors.servercentral.net
    addr: 204.93.249.148

network_static_dns_resolvers:
  - 192.168.31.1

network_static_routes:
  - to: default
    via: 192.168.31.1

network_static_interfaces:
  - name: eno1
    type: trunk
  - name: mgmt0
    type: vlan
    parent: eno1
    id: 99
    addrs:
      - 192.168.31.3/24
  - name: svcs0
    type: vlan
    parent: eno1
    id: 20
  - name: tel0
    type: vlan
    parent: eno1
    id: 30
  - name: dmz0
    type: vlan
    parent: eno1
    id: 35
  - name: peer0
    type: vlan
    parent: eno1
    id: 101

cni_networks:
  - name: mgmt
    parent: mgmt0
  - name: dmz
    parent: dmz0
  - name: svcs
    parent: svcs0
  - name: peering
    parent: peer0

nomad_volumes:
  - name: speedtest_data
    path: /nomad/speedtest
    read_only: false
  - name: ddns_data
    path: /nomad/ddns_data
    read_only: false
  - name: zwave_data
    path: /nomad/zwave_data
    read_only: false
  - name: esphome_data
    path: /nomad/esphome_data
    read_only: false
