---
network_output_policy: ACCEPT
network_input_policy: ACCEPT
network_forward_policy: ACCEPT
network_hostname: global-dynamics

network_boot_hosts:
  - name: mirrors.servercentral.net
    addr: 204.93.249.148

network_static_dns_resolvers:
  - 192.168.31.2

network_static_routes:
  - to: default
    via: 192.168.31.1

network_static_interfaces:
  - name: eno1
    type: trunk
  - name: mgmt0
    type: vlan
    parent: eno1
    id: 99
    addrs:
      - 192.168.31.3/24
  - name: dmz0
    type: vlan
    parent: eno1
    id: 35

podman_networks:
  - name: mgmt
    parent: mgmt0
  - name: dmz
    parent: dmz0
