---
network_output_policy: ACCEPT
network_hostname: psvcs.dal.michaelwashere.net

network_boot_hosts:
  - name: mirrors.servercentral.net
    addr: 204.93.249.148

network_static_dns_resolvers:
  - 8.8.8.8

network_static_interfaces:
  - name: enp1s0
    type: trunk
  - name: mgmt0
    type: vlan
    parent: enp1s0
    id: 99
    addrs:
      - 192.168.31.2/24
  - name: res0
    type: vlan
    parent: enp1s0
    id: 10
    addrs:
      - 192.168.16.2/24
  - name: guest0
    type: vlan
    parent: enp1s0
    id: 15
    addrs:
      - 192.168.17.2/24
  - name: svcs0
    type: vlan
    parent: enp1s0
    id: 20
    addrs:
      - 192.168.18.2/24
  - name: iot0
    type: vlan
    parent: enp1s0
    id: 25
    addrs:
      - 192.168.19.2/24
  - name: tel0
    type: vlan
    parent: enp1s0
    id: 30
    addrs:
      - 192.168.20.2/24
  - name: dmz0
    type: vlan
    parent: enp1s0
    id: 35
    addrs:
      - 192.168.21.2/24
  - name: peer0
    type: vlan
    parent: enp1s0
    id: 101
    addrs:
      - 169.254.255.254/24

network_static_routes:
  - to: default
    via: 192.168.18.1

nomad_datacenter: CONTROL

nomad_volumes:
  - name: dnsmasq_hosts
    path: /nomad/dnsmasq_hosts
    read_only: false
