---
- name: Configure firewall for InspIRCd
  copy:
    src: inspircd.rules
    dest: /etc/iptables.d/inspircd.rules
    owner: root
    group: root
    mode: 0640
  notify:
  - iptables

- name: Install InspIRCd
  xbps:
    pkg: inspircd
    state: present

- include_vars: secret/inspircd_opers.yml

- name: Configure InspIRCd
  template:
    src: "{{ item }}"
    dest: /etc/inspircd/{{ item }}
    owner: root
    group: inspircd
    mode: 0640
  with_items:
    - inspircd.conf
    - modules.conf
    - opers.conf
    - motd.txt
    - rules.txt
  notify:
      - inspircd

- name: Make data directory
  file:
    path: /etc/inspircd/{{ item }}
    state: directory
    owner: inspircd
    group: inspircd
    mode: 0700
  with_items:
    - data
    - logs

- name: Check for PermChans database
  stat:
    path: /etc/inspircd/data/permchannels.conf
  register: permchans

- name: Create PermChans database
  file:
    path: /etc/inspircd/data/permchannels.conf
    state: touch
    owner: inspircd
    group: inspircd
    mode: 0600
  when: permchans.stat.exists == false


- name: Enable InspIRCd
  service:
    name: inspircd
    enabled: true
