---
- name: Provision Persistence Volume
  community.docker.docker_volume:
    name: zwavejs-data

- name: Provision Container
  community.docker.docker_container:
    name: zwavejs
    image: docker.io/zwavejs/zwave-js-ui:9.21.0
    restart_policy: always
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave
    volumes:
      - zwavejs-data:/usr/src/app/store

- name: Install Firewall Rules
  ansible.builtin.copy:
    content: |
      *filter
      -A INPUT -p tcp --dport 8091 -j ACCEPT
      -A INPUT -p tcp --dport 3000 -j ACCEPT
      COMMIT
    dest: /etc/iptables.d/20-zwavejs.rules
    owner: root
    group: root
    mode: "0640"
