---
homeassistant:
  name: Greenhaven
  latitude: 32.9722
  longitude: -96.7376
  elevation: 203
  unit_system: imperial
  time_zone: America/Chicago

frontend:
http:
updater:
conversation:
history:
logbook:
sun:

light:
  - platform: x10
    devices:
      - id: a2
        name: Living Room Lamp
      - id: a9
        name: Party Light
  - platform: flux_led
    devices:
      10.0.1.50:
        name: LED Left
        mode: 'rgb'
      10.0.1.51:
        name: LED Right
        mode: 'rgb'
      10.0.1.52:
        name: Hall
        mode: 'rgb'
      10.0.1.53:
        name: Michael Bedroom
        mode: 'rgb'

group:
  Living Room LEDs:
    entities:
      - light.LED_Left
      - light.LED_Right

scene:
  - name: Party Mode
    entities:
      light.Living_Room_Lamp: off
      light.Party_Light: on
      group.Living_Room_LEDs: on
  - name: Home After Dark
    entities:
      group.Living_Room_LEDs: on
      light.Hall: on
      light.Michaels_Bedroom: on

device_tracker:
  - platform: ping
    hosts:
      maldridge: 10.0.1.11

device_sun_light_trigger:
  light_group: group.Living_Room_LEDs
