---
- name: Install php modules
  xbps:
    pkg:
      - php-gd
      - php-mcrypt
      - php-sqlite
    state: present

- name: Create the pydio group
  group:
    name: pydio
    state: present

- name: Create the pydio user
  user:
    name: pydio
    state: present
    group: pydio

- name: Add nginx to the pydio group
  user:
    name: nginx
    group: pydio

- name: Install nginx config file
  template:
    src: pydio.conf
    dest: /etc/nginx/sites-available/pydio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable nginx config file
  file:
    src: ../sites-available/pydio.conf
    dest: /etc/nginx/sites-enabled/pydio.conf
    state: link
  notify:
    - nginx

- name: Install the php-fpm pool config
  template:
    src: pydio.php-fpm
    dest: /etc/php/php-fpm.d/pydio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - php-fpm

- name: Install pydio php.ini
  template:
    src: pydio.ini
    dest: /etc/php/conf.d/pydio.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - php-fpm

- name: Copy pydio firewall rules
  copy:
    src: pydio.rules
    dest: /etc/iptables.d/pydio.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
