---
- name: Install php modules
  xbps:
    pkg:
      - php-gd
      - php-mcrypt
      - php-sqlite
    state: present

- name: Create the pydio group
  group:
    name: pydio
    state: present

- name: Create the pydio user
  user:
    name: pydio
    state: present
    group: pydio

- name: Add nginx to the pydio group
  user:
    name: nginx
    group: pydio

- name: Configure nginx
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: pydio
        urls: "{{ pydio_domain }}"
        use_ssl: true
        root_path: "{{ pydio_webroot }}"
        static_root: false
        ssl_certificate_path: "{{ pydio_certificate_path }}"
        ssl_key_path: "{{ pydio_key_path }}"
        ssl_stapling: "{{ pydio_ssl_stapling }}"
        

- name: Configure auxiliary nginx settings
  template:
    src: additional-settings.conf
    dest: "/etc/nginx/locations.d/{{ pydio_domain | first }}/"
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Configure nginx locations
  copy:
    src: pydio-locations.conf
    dest: "/etc/nginx/locations.d/{{ pydio_domain | first }}/"
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx
        
- name: Install the php-fpm pool config
  template:
    src: pydio.php-fpm
    dest: /etc/php/php-fpm.d/pydio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - php-fpm

- name: Install pydio php.ini
  template:
    src: pydio.ini
    dest: /etc/php/conf.d/pydio.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - php-fpm
