---
- name: Create State Directory
  file:
    path: /var/lib/p0rtalNet/containers/ddns
    state: directory
    owner: 1000
    group: root
    mode: 0755

- name: Install Config File
  copy:
    src: secret/ddns.json
    dest: /var/lib/p0rtalNet/containers/ddns/config.json
    owner: 1000
    group: root
    mode: 0400

- name: Install Container
  containers.podman.podman_container:
    name: ddns
    state: started
    image: ghcr.io/qdm12/ddns-updater:latest
    mac_address: 02:00:00:02:00:02
    network: svcs
    hostname: ddns-client
    cap_add:
      - NET_BIND_SERVICE
    dns:
      - 192.168.18.2
    volumes:
      - /var/lib/p0rtalNet/containers/ddns:/updater/data
