---
- name: Create Persistent Volume
  containers.podman.podman_volume:
    name: hass_data
    state: present

- name: Install Container
  containers.podman.podman_container:
    name: hass
    state: started
    restart_policy: always
    image: ghcr.io/home-assistant/home-assistant:2022.11.4
    mac_address: 02:00:00:02:00:03
    network: svcs
    env:
      TZ: America/Chicago
    dns:
      - 192.168.18.2
    volume:
      - hass_data:/config
