---
- name: Create group
  group:
    name: noobfarm
    state: present

- name: Create User
  user:
    name: noobfarm
    group: noobfarm
    createhome: yes
    home: /mnt/margarine/noobfarm2
    comment: Noobfarm service user

- name: Configure webserver
  include_role:
    name: "{{ VAR_webserver | default('nginx') }}"
    tasks_from: base-site
  vars:
    - site:
        name: noobfarm
        urls:
          - noobfarm.org
        tls:
          stapling: true
        proxy:
          - to: http://127.0.1.1:2001
            from: /

- name: Install Service (1/2)
  file:
    path: /etc/sv/noobfarm
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install Service (2/2)
  copy:
    src: run
    dest: /etc/sv/noobfarm/run
    owner: root
    group: root
    mode: 0755

- name: Enable services
  runit:
    name: noobfarm
    enabled: yes
