---
- name: Install Packages
  community.general.xbps:
    pkg:
      - docker
      - python3-requests
      - python3-docker
    state: present

- name: Enable Service
  ansible.builtin.runit:
    name: docker
    state: started
    enabled: true
