---
- hosts: static_ip
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - void.network.static
    - void.network.dns

- hosts: "all:!static_ip"
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - void.network.dhcpcd

- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - void.network.iptables
    - xbps-repoconf
    - sshd
