---
- hosts: container
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - podman

- hosts: globaldynamics
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - container-bastion
    - container-bird
    - container-ddns
    - container-hass
    - container-esphome
    - container-jellyfin
