---
network_interfaces:
  - name: default
    mode: static
    mode6: disabled
    resolvermode: static
    addresses:
      - 69.13.217.92/24
    routers:
      - 69.13.217.89

VAR_webserver: caddy

caddy:
  tls_hostmaster: aldridge.mac@gmail.com

hugo_sites:
  - name: netauth
    root_path: /srv/www/netauth
    urls:
      - netauth.org
      - www.netauth.org
    source_url: https://github.com/NetAuth/netauth.org
    source_port: 443
    tls:
      stapling: true
  - name: maldridge_us
    root_path: /srv/www/maldridge_us
    urls:
      - maldridge.us
    source_url: http://git.michaelwashere.net/maldridge/maldridge.us.git
    source_host: git.michaelwashere.net
    source_port: 443
    tls:
      stapling: true
  - name: mwh
    root_path: /srv/www/mwh
    urls:
      - michaelwashere.net
      - www.michaelwashere.net
    source_url: https://github.com/the-maldridge/mwh_site.git
    source_port: 443
    tls:
      stapling: true

mdbook_sites:
  - name: netauth_docs
    root_path: /srv/www/netauth_docs
    urls:
      - docs.netauth.org
    source_url: https://github.com/NetAuth/docs
    source_port: 443
    tls:
      stapling: true

xbps_mini_builder_pkgs: assets/config/xbps-mini-builder/packages.list
xbps_mini_builder_conf: assets/config/xbps-mini-builder/xbps-src.conf
xbps_mini_builder_servernames:
  - pkgs.michaelwashere.net

sshd_KexAlgorithms:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256
  - diffie-hellman-group14-sha1
