---
network_interfaces:
  - name: default
    mode: static
    mode6: disabled
    resolvermode: static
    addresses:
      - 69.13.217.92/24
    routers:
      - 69.13.217.89

pydio_domain: pydio.michaelwashere.net
pydio_webroot: /srv/www/pydio
pydio_certificate_path: /etc/letsencrypt/live/pydio.michaelwashere.net/fullchain.pem
pydio_key_path: /etc/letsencrypt/live/pydio.michaelwashere.net/privkey.pem

xbps_mini_builder_pkgs: assets/config/xbps-mini-builder/packages.list
xbps_mini_builder_conf: assets/config/xbps-mini-builder/xbps-src.conf
xbps_mini_builder_servername: pkgs.michaelwashere.net
