---
sg_pkg_server: mirrors.sonic.net
sg_pkg_path: https://{{ sg_pkg_server }}/%m/

sg_globalconf:
  hostname: edge01.mtv.michaelwashere.net
  domain_address: 10.0.1.1
  bootresolvers:
    - 8.8.8.8
    - 8.8.4.4
  pf:
    block_policy: drop
  dns:
    SOA: 2016120400
  ntp:
    clocks:
      - pool.ntp.org
  ssh:
    permit_password: false
    listen_egress: true

sg_networks:
  - name: home
    desc: Main Home Network
    cidr: 10.0.1.0/24
    arpa: 10.in-addr.arpa
    attach_to: bge0
    domain: mtv.michaelwashere.net
    services:
      - jumphost
      - nat
      - ssh
      - dhcp
      - dns
      - ntp
    serviceconf:
      dns:
        adminmail: mtv.michaelwashere.net
        domain_address: 10.0.1.1
        nameservers:
          - 10.0.1.1
      dhcp:
        pools:
          - 10.0.1.64/26
        routers: 10.0.1.1
        dns: 10.0.1.1
        ntp: 10.0.1.1
        allow_unknown: true
      nat:
        nat_to: fxp0
        mode: manual
        autonat:
          - 10.0.1.0/24
    hosts: "{{ mtv_hosts }}"


sg_interfaces:
  - name: fxp0
    desc: External Spectrum Link
    address: dhcp
  - name: bge0
    desc: p0rtalNet MTV Network
    address: 10.0.1.1/24

mtv_hosts:
  - name: GlobalDynamics
    mac: 00:1e:8c:89:78:75
    addr: 10.0.1.2
  - name: wireless
    mac: 04:18:d6:92:89:ae
    addr: 10.0.1.3
  - name: sip-gateway
    mac: 9c:ad:ef:12:32:a9
    addr: 10.0.1.4
  - name: unifi
    mac: f0:9f:c2:15:38:c4
    addr: 10.0.1.5
  - name: theGibson
    mac: bc:5f:f4:7b:59:21
    addr: 10.0.1.10
  - name: maldridgePhone
    mac: 64:bc:0c:43:03:b9
    addr: 10.0.1.11
  - name: earth
    mac: f0:1f:af:3a:ce:a6
    addr: 10.0.1.12
  - name: earth
    mac: 70:18:8b:b9:79:87
    addr: 10.0.1.13
  - name: maldridge-chromebook
    mac: 14:2d:27:65:60:af
    addr: 10.0.1.14
  - name: tradfri
    mac: b0:72:bf:27:90:9d
    addr: 10.0.1.54
