#!/bin/sh

RESTIC_REPO=/mnt/vault/restic/
RESTIC_MIRROR=/mnt/firevault/restic/
export HOME=$RESTIC_REPO
export RESTIC_PASSWORD_FILE=/etc/restic.passwd

if ! restic -r $RESTIC_REPO snapshots ; then
    # No repo, so we'll go ahead and create it
    restic init --repo $RESTIC_REPO
fi

# Backup shared data
restic -r $RESTIC_REPO backup --exclude nethomes /mnt/aluminium-mountain/

# Backup home folders
restic -r $RESTIC_REPO backup /mnt/aluminium-mountain/nethomes/maldridge

if ! restic -r $RESTIC_REPO check ; then
    # Restic encountered some kind of error
    touch /tmp/BACKUP_FAIL
    exit
fi

# Sync to the mirror
rsync -auv --delete $RESTIC_REPO $RESTIC_MIRROR
